/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app/home/home.module';
import * as import2 from 'angular2-grid/modules/NgGrid.module';
import * as import3 from '@angular/core/src/di/injector';
import * as import4 from '../../../node_modules/angular2-grid/components/NgGridPlaceholder.ngfactory';
class HomeModuleInjector extends import0.NgModuleInjector<import1.HomeModule> {
  _NgGridModule_0:import2.NgGridModule;
  _HomeModule_1:import1.HomeModule;
  constructor(parent:import3.Injector) {
    super(parent,[import4.NgGridPlaceholderNgFactory],([] as any[]));
  }
  createInternal():import1.HomeModule {
    this._NgGridModule_0 = new import2.NgGridModule();
    this._HomeModule_1 = new import1.HomeModule();
    return this._HomeModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.NgGridModule)) { return this._NgGridModule_0; }
    if ((token === import1.HomeModule)) { return this._HomeModule_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const HomeModuleNgFactory:import0.NgModuleFactory<import1.HomeModule> = new import0.NgModuleFactory(HomeModuleInjector,import1.HomeModule);