/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app/accountwidgetmodule/accountwidgetmodule';
import * as import2 from '@angular/core/src/di/injector';
import * as import3 from './accountwidgetcomponent.ngfactory';
class AccountWidgetModuleInjector extends import0.NgModuleInjector<import1.AccountWidgetModule> {
  _AccountWidgetModule_0:import1.AccountWidgetModule;
  constructor(parent:import2.Injector) {
    super(parent,[import3.AccountWidgetComponentNgFactory],([] as any[]));
  }
  createInternal():import1.AccountWidgetModule {
    this._AccountWidgetModule_0 = new import1.AccountWidgetModule();
    return this._AccountWidgetModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.AccountWidgetModule)) { return this._AccountWidgetModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AccountWidgetModuleNgFactory:import0.NgModuleFactory<import1.AccountWidgetModule> = new import0.NgModuleFactory(AccountWidgetModuleInjector,import1.AccountWidgetModule);